import { CustomerProfile, RiskRule, CaseInvestigatorData } from './types';

export const RISK_RULES: RiskRule[] = [
  {
    id: 'R001',
    name: 'Unusually Large Transfer',
    category: 'Amount Anomaly',
    description: "Single transaction > 2x customer's average",
    thresholdText: 'Amount > 2x customer baseline average',
  },
  {
    id: 'R002',
    name: 'New Payee Burst',
    category: 'Velocity & Recency',
    description: '3+ transactions to a payee in first 7 days',
    thresholdText: '≥ 3 transfers within 7 days of first payee appearance',
  },
  {
    id: 'R003',
    name: 'Odd Hours Activity',
    category: 'Temporal Anomaly',
    description: 'Transactions 11 PM - 5 AM break pattern',
    thresholdText: 'Timestamps between 23:00 - 05:00 local time',
  },
  {
    id: 'R004',
    name: 'Pattern Break',
    category: 'Merchant & Category',
    description: 'Transactions to unusual payee types',
    thresholdText: 'Non-routine beneficiary (e.g. Unverified Virtual Asset Services)',
  },
  {
    id: 'R005',
    name: 'Rapid Succession',
    category: 'Velocity Anomaly',
    description: 'Multiple large transfers within 1 hour',
    thresholdText: '≥ 2 large transfers (> 2x baseline) within a 60-minute window',
  },
];

export const CUST001: CustomerProfile = {
  id: 'CUST001',
  caseId: 'CUST001-2024-9901',
  name: 'Alex Vance',
  bankName: 'First National Bank of North America',
  accountNumber: '****-4920',
  accountType: 'Personal Checking',
  averageTransaction: 8000,
  monthlyIncome: 25000,
  riskRating: 'High',
  reviewStatus: 'PENDING INVESTIGATION',
  generatedAt: '2024-08-11 09:14:22 EST',
  transactions: [
    {
      id: 1,
      date: '2024-08-01',
      amount: 5000,
      payee: 'Amazon',
      channel: 'online',
      description: 'Shopping',
      notes: 'Standard e-commerce purchase',
    },
    {
      id: 2,
      date: '2024-08-02',
      amount: 25000,
      payee: 'Salary Deposit',
      channel: 'transfer',
      description: 'Monthly salary',
      notes: 'Inbound direct payroll credit',
    },
    {
      id: 3,
      date: '2024-08-05',
      amount: 50000,
      payee: 'Crypto Exchange XYZ',
      channel: 'online',
      description: 'Investment',
      notes: 'First time transaction to this payee',
      timeNote: 'Initial outbound transfer',
      isNewPayee: true,
    },
    {
      id: 4,
      date: '2024-08-05',
      amount: 45000,
      payee: 'Crypto Exchange XYZ',
      channel: 'online',
      description: 'Investment',
      notes: 'Same payee, 2 hours later',
      timeNote: '2 hours after Tx #3',
    },
    {
      id: 5,
      date: '2024-08-06',
      amount: 40000,
      payee: 'Crypto Exchange XYZ',
      channel: 'online',
      description: 'Investment',
      notes: 'Same payee, day later',
      timeNote: '1 day after Tx #3/4',
    },
    {
      id: 6,
      date: '2024-08-08',
      amount: 3200,
      payee: 'Electric Utility Co',
      channel: 'online',
      description: 'Utilities',
      notes: 'Monthly residential electricity bill',
    },
    {
      id: 7,
      date: '2024-08-09',
      amount: 1450,
      payee: 'Bistro Moderne',
      channel: 'debit_card',
      description: 'Dining',
      notes: 'Routine dining expense',
    },
    {
      id: 8,
      date: '2024-08-10',
      amount: 8500,
      payee: 'Whole Foods Market',
      channel: 'debit_card',
      description: 'Groceries',
      notes: 'Routine household debit card spending',
    },
  ],
};

export const CUST002: CustomerProfile = {
  id: 'CUST002',
  caseId: 'CUST002-2024-9902',
  name: 'Sarah Jenkins',
  bankName: 'Metropolitan Trust & Savings Bank',
  accountNumber: '****-7714',
  accountType: 'Personal Checking',
  averageTransaction: 6000,
  monthlyIncome: 18500,
  riskRating: 'None',
  reviewStatus: 'COMPLETE',
  generatedAt: '2024-08-11 08:30:15 EST',
  transactions: [
    {
      id: 1,
      date: '2024-08-01',
      amount: 4200,
      payee: 'Apex Property Management',
      channel: 'transfer',
      description: 'Residential Rent',
      notes: 'Scheduled monthly apartment lease payment',
    },
    {
      id: 2,
      date: '2024-08-02',
      amount: 18500,
      payee: 'Global Tech Direct Payroll',
      channel: 'transfer',
      description: 'Monthly Salary',
      notes: 'Routine direct deposit payroll credit',
    },
    {
      id: 3,
      date: '2024-08-03',
      amount: 1250,
      payee: "Trader Joe's",
      channel: 'debit_card',
      description: 'Groceries',
      notes: 'Weekly routine groceries',
    },
    {
      id: 4,
      date: '2024-08-04',
      amount: 380,
      payee: 'City Water & Power',
      channel: 'online',
      description: 'Utilities',
      notes: 'Monthly municipal utility bill',
    },
    {
      id: 5,
      date: '2024-08-05',
      amount: 890,
      payee: 'Target Retail Store',
      channel: 'debit_card',
      description: 'Shopping',
      notes: 'Standard household supplies',
    },
    {
      id: 6,
      date: '2024-08-07',
      amount: 520,
      payee: 'Shell Fuel Station',
      channel: 'debit_card',
      description: 'Transportation',
      notes: 'Regular vehicle fuel replenishment',
    },
    {
      id: 7,
      date: '2024-08-08',
      amount: 1800,
      payee: 'Apple Retail Store',
      channel: 'online',
      description: 'Electronics',
      notes: 'Hardware accessories replacement',
    },
    {
      id: 8,
      date: '2024-08-09',
      amount: 4500,
      payee: 'Vanguard Investments',
      channel: 'transfer',
      description: 'Retirement Savings',
      notes: 'Scheduled monthly automatic IRA contribution',
    },
  ],
};

export const CUST003: CustomerProfile = {
  id: 'CUST003',
  caseId: 'CUST003-2024-9903',
  name: 'Marcus Brody',
  bankName: 'Pacific Commercial Merchant Bank',
  accountNumber: '****-3190',
  accountType: 'Business Checking',
  averageTransaction: 12000,
  monthlyIncome: 45000,
  riskRating: 'High',
  reviewStatus: 'PENDING INVESTIGATION',
  generatedAt: '2024-08-11 10:05:00 EST',
  transactions: [
    {
      id: 1,
      date: '2024-08-01',
      amount: 8500,
      payee: 'Office Depot & Supplies',
      channel: 'debit_card',
      description: 'Operations',
      notes: 'Quarterly office equipment and consumables',
    },
    {
      id: 2,
      date: '2024-08-02',
      amount: 45000,
      payee: 'Client Retainer Wire Inbound',
      channel: 'transfer',
      description: 'Revenue Deposit',
      notes: 'Verified commercial enterprise client retainer deposit',
    },
    {
      id: 3,
      date: '2024-08-04',
      amount: 65000,
      payee: 'Apex Pacific Trading Ltd',
      channel: 'transfer',
      description: 'International Wire',
      notes: 'Offshore beneficiary wire',
      timeNote: 'Executed at 02:15 AM (Odd Hours)',
      isNewPayee: true,
    },
    {
      id: 4,
      date: '2024-08-04',
      amount: 72000,
      payee: 'Apex Pacific Trading Ltd',
      channel: 'transfer',
      description: 'International Wire',
      notes: 'Second consecutive wire, 35 minutes after Tx #3',
      timeNote: 'Executed at 02:50 AM (35 mins after Tx #3)',
    },
    {
      id: 5,
      date: '2024-08-06',
      amount: 9400,
      payee: 'Commercial Real Estate Lease',
      channel: 'transfer',
      description: 'Rent',
      notes: 'Monthly headquarters commercial office lease',
    },
    {
      id: 6,
      date: '2024-08-07',
      amount: 3800,
      payee: 'Cloud Computing Services Inc',
      channel: 'online',
      description: 'IT Infrastructure',
      notes: 'Monthly enterprise hosting and database cluster',
    },
    {
      id: 7,
      date: '2024-08-08',
      amount: 1650,
      payee: 'Executive Travel Airline',
      channel: 'online',
      description: 'Travel',
      notes: 'Domestic client consultation flight booking',
    },
    {
      id: 8,
      date: '2024-08-09',
      amount: 11200,
      payee: 'Staff Health Insurance Co',
      channel: 'transfer',
      description: 'Payroll / Benefits',
      notes: 'Monthly employee group medical coverage',
    },
  ],
};

export const CASES_LIST: CustomerProfile[] = [CUST001, CUST002, CUST003];

export const INITIAL_INVESTIGATOR_DATA: Record<string, CaseInvestigatorData> = {
  CUST001: {
    notes: 'Case flagged by automated heuristics engine following $135,000 cumulative outbound transfers across 3 transactions to a newly added virtual asset payee. Recommend out-of-band contact with Alex Vance to verify transaction intent before releasing any further wire instructions.',
    checklist: {
      customerContacted: false,
      intentConfirmed: false,
      deviceVerified: false,
      mfaReviewed: false,
    },
    decision: 'INVESTIGATE',
    assignedInvestigator: 'M. Chen (AML Analyst II)',
    lastSaved: '2024-08-11 09:30 EST',
  },
  CUST002: {
    notes: 'Routine periodic transaction risk review completed. Account spending patterns strictly match historical baseline. All beneficiaries are established merchants, verified payroll, and scheduled utility/rent payments. No anomalous velocity or new payee spikes observed.',
    checklist: {
      customerContacted: true,
      intentConfirmed: true,
      deviceVerified: true,
      mfaReviewed: true,
    },
    decision: 'CLEAR',
    assignedInvestigator: 'S. Patel (Senior Compliance Specialist)',
    lastSaved: '2024-08-11 08:45 EST',
  },
  CUST003: {
    notes: 'High risk alert generated for multiple anomalous outbound wires totaling $137,000 initiated during nocturnal hours (02:15 - 02:50 AM) to offshore entity Apex Pacific Trading. Corporate signing officer contacted; awaiting verification of commercial invoice legitimacy.',
    checklist: {
      customerContacted: false,
      intentConfirmed: false,
      deviceVerified: true,
      mfaReviewed: true,
    },
    decision: 'ESCALATE',
    assignedInvestigator: 'D. Miller (Lead Risk Officer)',
    lastSaved: '2024-08-11 10:15 EST',
  },
};

export const INVESTIGATOR_OPTIONS = [
  'M. Chen (AML Analyst II)',
  'S. Patel (Senior Compliance Specialist)',
  'D. Miller (Lead Risk Officer)',
  'J. Alvarez (Special Investigations Unit)',
];
